# Generated by Django 6.1 on 2026-08-09 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="habits",
                to="habits.place",
                verbose_name="Место выполнения",
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(fields=["owner"], name="habits_plac_owner_i_ba3643_idx"),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(fields=["owner"], name="habits_habi_owner_i_c2c5d4_idx"),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["is_public"], name="habits_habi_is_publ_af85bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["is_active"], name="habits_habi_is_acti_7e65cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["owner", "is_active"], name="habits_habi_owner_i_ab900c_idx"
            ),
        ),
    ]
