# Generated by Django 6.1 on 2026-08-09 13:47

import apps.habits.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="name",
            field=models.CharField(
                default="Новая привычка",
                max_length=100,
                validators=[apps.habits.models.validate_habit],
            ),
        ),
    ]
