# Generated by Django 6.1 on 2026-08-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="name",
            field=models.CharField(
                help_text="Уникальное название для привычки",
                max_length=100,
                verbose_name="Название привычки",
            ),
        ),
    ]
