# Generated by Django 6.1 on 2026-08-09 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("telegram_bot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="telegramuser",
            index=models.Index(
                fields=["chat_id"], name="telegram_bo_chat_id_541234_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="telegramuser",
            index=models.Index(
                fields=["is_active"], name="telegram_bo_is_acti_f40713_idx"
            ),
        ),
    ]
